# Generated by Django 5.1.6 on 2025-03-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilisateur', '0002_alter_client_photo_profil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.AutoField(primary_key=True, serialize=False)),
                ('nom_specialite', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='specialite')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('prix_heure', models.FloatField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.professeur')),
                ('id_specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Specialite.specialite')),
            ],
        ),
    ]
